package entity;
// Generated 26 mai 2019 18:05:50 by Hibernate Tools 4.3.1



/**
 * ActiviteTProduitFini generated by hbm2java
 */
public class ActiviteTProduitFini  implements java.io.Serializable {


     private Long id;
     private Long idActiviteT;
     private String nomProduitFini;
     private String datecreat;
     private String admin;

    public ActiviteTProduitFini() {
    }

    public ActiviteTProduitFini(Long idActiviteT, String nomProduitFini, String datecreat, String admin) {
       this.idActiviteT = idActiviteT;
       this.nomProduitFini = nomProduitFini;
       this.datecreat = datecreat;
       this.admin = admin;
    }

    public ActiviteTProduitFini(Long id, Long idActiviteT, String nomProduitFini, String datecreat, String admin) {
        this.id = id;
        this.idActiviteT = idActiviteT;
        this.nomProduitFini = nomProduitFini;
        this.datecreat = datecreat;
        this.admin = admin;
    }
    
    
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getIdActiviteT() {
        return this.idActiviteT;
    }
    
    public void setIdActiviteT(Long idActiviteT) {
        this.idActiviteT = idActiviteT;
    }
    public String getNomProduitFini() {
        return this.nomProduitFini;
    }
    
    public void setNomProduitFini(String nomProduitFini) {
        this.nomProduitFini = nomProduitFini;
    }
    public String getDatecreat() {
        return this.datecreat;
    }
    
    public void setDatecreat(String datecreat) {
        this.datecreat = datecreat;
    }
    public String getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(String admin) {
        this.admin = admin;
    }




}


