package entity;
// Generated 26 mai 2019 18:05:50 by Hibernate Tools 4.3.1



/**
 * Clients generated by hbm2java
 */
public class Clients  implements java.io.Serializable {


     private Integer id;
     private String entreprise;
     private String nomCourt;
     private String adresse;
     private String tel1;
     private String tel2;
     private String email;
     private String fonction;
     private String description;
     private Long plafonCredit;
     private String datecreat;
     private String admin;

    public Clients() {
    }

    public Clients(String entreprise, String nomCourt, String adresse, String tel1, String tel2, String email, String fonction, String description, Long plafonCredit, String datecreat, String admin) {
       this.entreprise = entreprise;
       this.nomCourt = nomCourt;
       this.adresse = adresse;
       this.tel1 = tel1;
       this.tel2 = tel2;
       this.email = email;
       this.fonction = fonction;
       this.description = description;
       this.plafonCredit = plafonCredit;
       this.datecreat = datecreat;
       this.admin = admin;
    }

    public Clients(Integer id, String entreprise, String nomCourt, String adresse, String tel1, String tel2, String email, String fonction, String description, Long plafonCredit, String datecreat, String admin) {
        this.id = id;
        this.entreprise = entreprise;
        this.nomCourt = nomCourt;
        this.adresse = adresse;
        this.tel1 = tel1;
        this.tel2 = tel2;
        this.email = email;
        this.fonction = fonction;
        this.description = description;
        this.plafonCredit = plafonCredit;
        this.datecreat = datecreat;
        this.admin = admin;
    }
    
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(String entreprise) {
        this.entreprise = entreprise;
    }
    public String getNomCourt() {
        return this.nomCourt;
    }
    
    public void setNomCourt(String nomCourt) {
        this.nomCourt = nomCourt;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getTel1() {
        return this.tel1;
    }
    
    public void setTel1(String tel1) {
        this.tel1 = tel1;
    }
    public String getTel2() {
        return this.tel2;
    }
    
    public void setTel2(String tel2) {
        this.tel2 = tel2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Long getPlafonCredit() {
        return this.plafonCredit;
    }
    
    public void setPlafonCredit(Long plafonCredit) {
        this.plafonCredit = plafonCredit;
    }
    public String getDatecreat() {
        return this.datecreat;
    }
    
    public void setDatecreat(String datecreat) {
        this.datecreat = datecreat;
    }
    public String getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(String admin) {
        this.admin = admin;
    }




}


