package entity;
// Generated 26 mai 2019 18:05:50 by Hibernate Tools 4.3.1



/**
 * Magasins generated by hbm2java
 */
public class Magasins  implements java.io.Serializable {


     private Long id;
     private String magasin;
     private String datec;
     private String admin;
     private String etat;

    public Magasins() {
    }

    public Magasins(String magasin, String datec, String admin,  String etat) {
       this.magasin = magasin;
       this.datec = datec;
       this.admin = admin;
       this.etat = etat ;
    }

    public Magasins(Long id, String magasin, String datec, String admin, String etat) {
        this.id = id;
        this.magasin = magasin;
        this.datec = datec;
        this.admin = admin;
        this.etat = etat;
    }
    
    
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getMagasin() {
        return this.magasin;
    }
    
    public void setMagasin(String magasin) {
        this.magasin = magasin;
    }
    public String getDatec() {
        return this.datec;
    }
    
    public void setDatec(String datec) {
        this.datec = datec;
    }
    public String getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(String admin) {
        this.admin = admin;
    }

    public String getEtat() {
        return etat;
    }

    public void setEtat(String etat) {
        this.etat = etat;
    }




}


