package entity;
// Generated 26 mai 2019 18:05:50 by Hibernate Tools 4.3.1



/**
 * Ppf generated by hbm2java
 */
public class Ppf  implements java.io.Serializable {


     private Long id;
     private Long idp;
     private String nomp;
     private String cb;
     private String article;
     private Long pa;
     private Long pu;
     private String datec;
     private String admin;
     private Integer idpf;

    public Ppf() {
    }

    public Ppf(Long idp, String nomp, String cb, String article, Long pa, Long pu, String datec, String admin, Integer idpf) {
       this.idp = idp;
       this.nomp = nomp;
       this.cb = cb;
       this.article = article;
       this.pa = pa;
       this.pu = pu;
       this.datec = datec;
       this.admin = admin;
       this.idpf = idpf ;
    }

    public Ppf(Long id, Long idp, String nomp, String cb, String article, Long pa, Long pu, String datec, String admin, Integer idpf) {
        this.id = id;
        this.idp = idp;
        this.nomp = nomp;
        this.cb = cb;
        this.article = article;
        this.pa = pa;
        this.pu = pu;
        this.datec = datec;
        this.admin = admin;
        this.idpf = idpf ;
    }
    
    
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getIdp() {
        return this.idp;
    }
    
    public void setIdp(Long idp) {
        this.idp = idp;
    }
    public String getNomp() {
        return this.nomp;
    }
    
    public void setNomp(String nomp) {
        this.nomp = nomp;
    }
    public String getCb() {
        return this.cb;
    }
    
    public void setCb(String cb) {
        this.cb = cb;
    }
    public String getArticle() {
        return this.article;
    }
    
    public void setArticle(String article) {
        this.article = article;
    }
    public Long getPa() {
        return this.pa;
    }
    
    public void setPa(Long pa) {
        this.pa = pa;
    }
    public Long getPu() {
        return this.pu;
    }
    
    public void setPu(Long pu) {
        this.pu = pu;
    }
    public String getDatec() {
        return this.datec;
    }
    
    public void setDatec(String datec) {
        this.datec = datec;
    }
    public String getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(String admin) {
        this.admin = admin;
    }

    public Integer getIdpf() {
        return idpf;
    }

    public void setIdpf(Integer idpf) {
        this.idpf = idpf;
    }




}


