package entity;
// Generated 26 mai 2019 18:05:50 by Hibernate Tools 4.3.1



/**
 * ProduitsF generated by hbm2java
 */
public class ProduitsF  implements java.io.Serializable {


     private Integer id;
     private String codeBarre;
     private Long libelle;
     private String description;
     private Long pu;
     private String uniteM;
     private String datecreat;
     private String admin;
     private String f;
     private String sf;
     private Integer stockMini;
     private Long idf;
     private Long idsf;

    public ProduitsF() {
    }

    public ProduitsF(String codeBarre, Long libelle, String description, Long pu, String uniteM, String datecreat, String admin, String f, String sf, Integer stockMini) {
       this.codeBarre = codeBarre;
       this.libelle = libelle;
       this.description = description;
       this.pu = pu;
       this.uniteM = uniteM;
       this.datecreat = datecreat;
       this.admin = admin;
       this.f = f;
       this.sf = sf;
       this.stockMini = stockMini;
    }
    public ProduitsF(String codeBarre, Long libelle, String description, Long pu, String uniteM, String datecreat, String admin, String f, String sf, Integer stockMini, Long idf , Long idsf) {
       this.codeBarre = codeBarre;
       this.libelle = libelle;
       this.description = description;
       this.pu = pu;
       this.uniteM = uniteM;
       this.datecreat = datecreat;
       this.admin = admin;
       this.f = f;
       this.sf = sf;
       this.stockMini = stockMini;
       this.idf = idf ;
       this.idsf = idsf ;
    }

    public ProduitsF(Integer id, String codeBarre, Long libelle, String description, Long pu, String uniteM, String datecreat, String admin, String f, String sf, Integer stockMini) {
        this.id = id;
        this.codeBarre = codeBarre;
        this.libelle = libelle;
        this.description = description;
        this.pu = pu;
        this.uniteM = uniteM;
        this.datecreat = datecreat;
        this.admin = admin;
        this.f = f;
        this.sf = sf;
        this.stockMini = stockMini;
    }
    
     public ProduitsF(Integer id, String codeBarre, Long libelle, String description, Long pu, String uniteM, String datecreat, String admin, String f, String sf, Integer stockMini, Long idf , Long idsf) {
        this.id = id;
        this.codeBarre = codeBarre;
        this.libelle = libelle;
        this.description = description;
        this.pu = pu;
        this.uniteM = uniteM;
        this.datecreat = datecreat;
        this.admin = admin;
        this.f = f;
        this.sf = sf;
        this.stockMini = stockMini;
        this.idf = idf ;
        this.idsf = idsf ;
    }
    
    
    
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodeBarre() {
        return this.codeBarre;
    }
    
    public void setCodeBarre(String codeBarre) {
        this.codeBarre = codeBarre;
    }
    public Long getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(Long libelle) {
        this.libelle = libelle;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Long getPu() {
        return this.pu;
    }
    
    public void setPu(Long pu) {
        this.pu = pu;
    }
    public String getUniteM() {
        return this.uniteM;
    }
    
    public void setUniteM(String uniteM) {
        this.uniteM = uniteM;
    }
    public String getDatecreat() {
        return this.datecreat;
    }
    
    public void setDatecreat(String datecreat) {
        this.datecreat = datecreat;
    }
    public String getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(String admin) {
        this.admin = admin;
    }
    public String getF() {
        return this.f;
    }
    
    public void setF(String f) {
        this.f = f;
    }
    public String getSf() {
        return this.sf;
    }
    
    public void setSf(String sf) {
        this.sf = sf;
    }
    public Integer getStockMini() {
        return this.stockMini;
    }
    
    public void setStockMini(Integer stockMini) {
        this.stockMini = stockMini;
    }

    public Long getIdf() {
        return idf;
    }

    public void setIdf(Long idf) {
        this.idf = idf;
    }

    public Long getIdsf() {
        return idsf;
    }

    public void setIdsf(Long idsf) {
        this.idsf = idsf;
    }




}


