package entity;
// Generated 26 mai 2019 18:05:50 by Hibernate Tools 4.3.1



/**
 * TransformationTProduitFini generated by hbm2java
 */
public class TransformationTProduitFini  implements java.io.Serializable {


     private Long id;
     private Long idActivT;
     private String produitFini;
     private Double prxUnitVent;
     private Double qteObt;
     private String unite;
     private String status;
     private String date;
     private String mois;
     private String annee;
     private String admin;

    public TransformationTProduitFini() {
    }

    public TransformationTProduitFini(Long idActivT, String produitFini, Double prxUnitVent, Double qteObt, String unite, String status, String date, String mois, String annee, String admin) {
       this.idActivT = idActivT;
       this.produitFini = produitFini;
       this.prxUnitVent = prxUnitVent;
       this.qteObt = qteObt;
       this.unite = unite;
       this.status = status;
       this.date = date;
       this.mois = mois;
       this.annee = annee;
       this.admin = admin;
    }

    public TransformationTProduitFini(Long id, Long idActivT, String produitFini, Double prxUnitVent, Double qteObt, String unite, String status, String date, String mois, String annee, String admin) {
        this.id = id;
        this.idActivT = idActivT;
        this.produitFini = produitFini;
        this.prxUnitVent = prxUnitVent;
        this.qteObt = qteObt;
        this.unite = unite;
        this.status = status;
        this.date = date;
        this.mois = mois;
        this.annee = annee;
        this.admin = admin;
    }
    
    
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getIdActivT() {
        return this.idActivT;
    }
    
    public void setIdActivT(Long idActivT) {
        this.idActivT = idActivT;
    }
    public String getProduitFini() {
        return this.produitFini;
    }
    
    public void setProduitFini(String produitFini) {
        this.produitFini = produitFini;
    }
    public Double getPrxUnitVent() {
        return this.prxUnitVent;
    }
    
    public void setPrxUnitVent(Double prxUnitVent) {
        this.prxUnitVent = prxUnitVent;
    }
    public Double getQteObt() {
        return this.qteObt;
    }
    
    public void setQteObt(Double qteObt) {
        this.qteObt = qteObt;
    }
    public String getUnite() {
        return this.unite;
    }
    
    public void setUnite(String unite) {
        this.unite = unite;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getMois() {
        return this.mois;
    }
    
    public void setMois(String mois) {
        this.mois = mois;
    }
    public String getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(String annee) {
        this.annee = annee;
    }
    public String getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(String admin) {
        this.admin = admin;
    }




}


