package entity;
// Generated 26 mai 2019 18:05:50 by Hibernate Tools 4.3.1



/**
 * Txxt generated by hbm2java
 */
public class Txxt  implements java.io.Serializable {


     private Integer id;
     private String f;
     private String sf;
     private String desi;
     private Integer qte;
     private Integer pa;
     private Integer pv;
     private Integer mu;
     private Integer profil;
     private String periode;

    public Txxt() {
    }

    public Txxt(String f, String sf, String desi, Integer qte, Integer pa, Integer pv, Integer mu, Integer profil, String periode) {
       this.f = f;
       this.sf = sf;
       this.desi = desi;
       this.qte = qte;
       this.pa = pa;
       this.pv = pv;
       this.mu = mu;
       this.profil = profil;
       this.periode = periode;
    }

    public Txxt(Integer id, String f, String sf, String desi, Integer qte, Integer pa, Integer pv, Integer mu, Integer profil, String periode) {
        this.id = id;
        this.f = f;
        this.sf = sf;
        this.desi = desi;
        this.qte = qte;
        this.pa = pa;
        this.pv = pv;
        this.mu = mu;
        this.profil = profil;
        this.periode = periode;
    }
    
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getF() {
        return this.f;
    }
    
    public void setF(String f) {
        this.f = f;
    }
    public String getSf() {
        return this.sf;
    }
    
    public void setSf(String sf) {
        this.sf = sf;
    }
    public String getDesi() {
        return this.desi;
    }
    
    public void setDesi(String desi) {
        this.desi = desi;
    }
    public Integer getQte() {
        return this.qte;
    }
    
    public void setQte(Integer qte) {
        this.qte = qte;
    }
    public Integer getPa() {
        return this.pa;
    }
    
    public void setPa(Integer pa) {
        this.pa = pa;
    }
    public Integer getPv() {
        return this.pv;
    }
    
    public void setPv(Integer pv) {
        this.pv = pv;
    }
    public Integer getMu() {
        return this.mu;
    }
    
    public void setMu(Integer mu) {
        this.mu = mu;
    }
    public Integer getProfil() {
        return this.profil;
    }
    
    public void setProfil(Integer profil) {
        this.profil = profil;
    }
    public String getPeriode() {
        return this.periode;
    }
    
    public void setPeriode(String periode) {
        this.periode = periode;
    }




}


