/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import static frontend.ListOp_En_Cours.JDBC_DRIVER;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author HAMZA
 */
public class Decoupage extends javax.swing.JFrame {

      static final String JDBC_DRIVER = "com.mysql.jdbc.Driver" ;  
      static final String DB_URL = "jdbc:mysql://192.168.1.117:3306/transformation" ;
      static final String USER = "root" ;
      static final String PASS = "interco" ;
      
      String login ;
      Integer cb_op ;
      String description = "" ;
      long qte ;
   // long pu ;
      float pu ;
   // long mtt ;
      float mtt ;
      Integer nbp_ob = 0 ;
   // long pu_p = 0 ;
      float pu_p ;
      float p_m_d ;
      
      
      String magasin_arriver = "" ;
      long oldStock_arriver = 0 ;
      long newStock_arriver = 0 ;
  //  long old_prx_pm_arriver = 0 ;
      float old_prx_pm_arriver = 0 ;
  //  long new_prx_pm_arriver = 0 ;
      float new_prx_pm_arriver = 0 ;
      Integer vy ;
      
      
      private ArrayList<String> list_d = new ArrayList<String>() ;
      
      private long ans ;
      private Integer id_st ;
      
    public Decoupage() {
        initComponents();
    }
    
    
    
     public Decoupage(String login , Integer cb_op , ArrayList<String> list_d){
        initComponents();
        
        this.login = login ;
        this.cb_op = cb_op ;
        this.list_d = list_d ;
       
       
        
        this.setLocationRelativeTo(null) ;
        
        for(int i = 0 ; this.list_d.size() > i ; i++){
            
            this.jComboBox1.addItem(new String(this.list_d.get(i).toString())) ;
            
        }
        
        
               Connection conn = null ;
               Statement  stmt = null  ;
       
       try{
      //STEP 2: Register JDBC driver
      Class.forName(JDBC_DRIVER) ;

      //STEP 3: Open a connection
     // System.out.println("Connecting to database...") ;
      
      conn = DriverManager.getConnection(DB_URL,USER,PASS) ;

      //STEP 4: Execute a query
      //System.out.println("Creating statement...");
      
      stmt = conn.createStatement() ;
      
      //je crai ma requete
      
       NumberFormat nf3 = NumberFormat.getInstance(new Locale("da", "DK")) ;
      
      
      
     String sql ;
     ResultSet rs ;
      
      sql = "select * from detail_pl where cb_op = "+this.cb_op+" and type = 'oui'" ;
      rs = stmt.executeQuery(sql) ;
      while(rs.next()){
       
          this.mtt += rs.getLong("mtt") ;
          
      }
      
      
       
     
    
      this.op.setText("OPERATEUR : "+this.login) ;
      
      
      
      
       sql = "select placement from point_pl where not placement = 'ZONE DE DECOUPAGE' AND not placement = 'EXTERIEUR' and type = 'oui' order by placement ASC" ;
                 ResultSet rs20 = stmt.executeQuery(sql) ;
                 
                 while(rs20.next()){
                 
                  this.jComboBox2.addItem(rs20.getString("placement")) ;
                  
                  
               
       }
      
                 
                 this.m.setText("MONTANT OPERATION : "+nf3.format(this.mtt)) ;
                 
      
      // fin partie unitile :
      
      
          
      // STEP 6: Clean-up environment
 
    // rs.close() ;
       stmt.close();
       conn.close();
      
      
   }catch(SQLException se){
      //Handle errors for JDBC
      se.printStackTrace();
   }catch(Exception e){
      //Handle errors for Class.forName
      e.printStackTrace();
   }finally{
      //finally block used to close resources
      try{
         if(stmt!=null)
            stmt.close();
      }catch(SQLException se2){
      }// nothing we can do
      try{
         if(conn!=null)
            conn.close();
      }catch(SQLException se){
         se.printStackTrace();
      }//end finally try
   }//end try
        
        
        
    // end saveing .....
        
                       
        
        
        
        
    }
     
     
     
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        m = new javax.swing.JLabel();
        nb = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        op = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nbp = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "FIN DU DECOUPAGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18)))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMATIONS GENERALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        m.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        m.setText("MONTANT OPERATION : ");

        nb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nb.setText("PORTION OBTENUE  :   0");

        p2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        p2.setText("PRIX MOYEN  :");

        op.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        op.setText("OPERATEUR  :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nb, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(op)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SAISIE DU NOMBRE OBTENU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

        nbp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        nbp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nbp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nbpKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel7.setText("QTE");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("VALIDER");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PRODUIT DERIVE" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "POINT PLACEMENT" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nbp, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nbpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nbpKeyReleased
        // TODO add your handling code here:
        
        try{
            
            String nbp ;
                   nbp = this.nbp.getText().trim() ;
                   this.nbp_ob = Integer.parseInt(nbp) ;
                   
                   if(this.nbp_ob <= 0){
                       JOptionPane.showMessageDialog(this, "NEGATIF ET NULL NON ACCEPTER") ;
                   }else{
                       
                       NumberFormat nf3 = NumberFormat.getInstance(new Locale("da", "DK")) ;
                       
                       this.pu_p = (this.mtt / this.nbp_ob) ;
                       this.nb.setText("PORTION OBTENUE :   "+nf3.format(this.nbp_ob)) ;
                       this.p2.setText("PRIX MOYEN : "+nf3.format(this.pu_p)) ;
                       
                       
                   }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "CHIFFRE UNIQUEMENT !!! ") ;
        }
        
        
    }//GEN-LAST:event_nbpKeyReleased
float ap = 0 ;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.ap = 0 ;
        
        this.id_st = 0 ;
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss") ;
        String jour2 = dt.format(new Date()) ;
        
        if(this.magasin_arriver.equalsIgnoreCase("") || this.jComboBox1.getSelectedItem().toString().equalsIgnoreCase("PRODUIT DERIVE") || this.description.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "PRECISER MAGASIN ET DERIVE !") ;
        }else{
        
        if(JOptionPane.showConfirmDialog(null, "VOULEZ-VOUS VALIDER LES : "+this.nbp_ob+" PORTIONS ?" , "AVERTISSEMENT" , JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            // yes option :
            
               Connection conn = null ;
               Statement  stmt = null  ;
       
       try{
      //STEP 2: Register JDBC driver
      Class.forName(JDBC_DRIVER) ;

      //STEP 3: Open a connection
     // System.out.println("Connecting to database...") ;
      
      conn = DriverManager.getConnection(DB_URL,USER,PASS) ;

      //STEP 4: Execute a query
      //System.out.println("Creating statement...");
      
      stmt = conn.createStatement() ;
      
      //je crai ma requete
      
      
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss") ;
      String jour ;
             jour = sdf.format(new Date()) ;
             
             this.ans = 0 ;
             
             String query = null ;
             ResultSet resultat = null ;
             
             String sql = null ;
             ResultSet rs = null ;
             
              this.vy = 0 ;
      
      
     
      
      
     sql = "select * from stock_pl where magasin = 'CHAMBRE FROIDE' and description = '"+this.description.replaceAll("'", "''")+"'" ;
     rs = stmt.executeQuery(sql) ;
     while(rs.next()){
     
      // this.magasin_arriver = rs.getString("magasin") ;
    //   this.description = rs.getString("description") ;
         
         this.id_st = rs.getInt("id") ;
         this.oldStock_arriver = rs.getLong("stock_dispo") ;
         this.old_prx_pm_arriver = rs.getLong("prx_pm") ;
         this.p_m_d = rs.getFloat("p_m_d") ;
         
         this.vy = 1 ;
         
     }
     
     
     sql = "select * from stock_pl where description = '"+this.description.replaceAll("'", "''")+"'  limit 2" ;
     rs = stmt.executeQuery(sql) ;
     while(rs.next()){
      
         this.ap = rs.getFloat("prx_pm") ;
       
          }
     
     
             
      int point = 0 ;       
             
query = "select stock_dispo from stock_pl where magasin = '"+this.magasin_arriver.replaceAll("'", "''")+"' and description = '"+this.description.replaceAll("'", "''")+"'" ;
resultat = stmt.executeQuery(query) ;
while(resultat.next()){
    this.ans = resultat.getLong("stock_dispo") ;
    point = 1 ;
}
      
     //  NumberFormat nf3 = NumberFormat.getInstance(new Locale("da", "DK")) ;
      
      try{
          
      if(this.vy == 0){
          
          if(point == 0){
          
          this.newStock_arriver = this.nbp_ob ;
          this.new_prx_pm_arriver = this.pu_p ;
          
          if(stmt.executeUpdate("insert into stock_pl(magasin,description,stock_dispo,prx_pm,dtec,admin, p_m_d) values('"
                  +this.magasin_arriver+"' , '"+this.description+"' , "+this.newStock_arriver+" , "+this.new_prx_pm_arriver+" , '"
                  +jour+"' , '"+this.login.replaceAll("'", "''")+"' , "+this.pu_p+")") == 1){
              
              
 stmt.executeUpdate("update stock_pl set prx_pm = "+this.new_prx_pm_arriver+" , p_m_d = "+this.new_prx_pm_arriver+" where description = '"+this.description.replaceAll("'", "''")+"'") ;
 stmt.executeUpdate("update stock_pl set ap = "+this.ap+" where description = '"+this.description.replaceAll("'", "''")+"'") ;
              
              
               if(stmt.executeUpdate("insert into stock_detail_pl(cb_op,datej,description,qte,prx_pm,mtt,depart,ndep,arriver,nariv,nderive,perso,type_op,admin, p_m_d, ans_2) VALUES("
                  +this.cb_op+" , '"+jour+"' , '"+this.description+"' , "+this.nbp_ob+" , "
          +this.pu_p+" , "+(this.nbp_ob * this.pu_p)+" , 'ZONE DE DECOUPAGE' , "
          +this.nbp_ob+" , '"+this.magasin_arriver+"' , "+this.nbp_ob+" , "+this.nbp_ob+" , '"
          +"PERSO T"+"' , 'entree' , '"
          + this.login.replaceAll("'", "''")+"' , "+this.pu_p+" , "+this.ans+")" ) == 1 ){
                 
                                              
                                         
                                         // fin detail stock placement :
                                              
                                         // debut detail_pl :
                                             
                   
             if(stmt.executeUpdate("update op_pl_f set etat = 'fermer' where cb = "+this.cb_op) == 1){
                 
                 this.jComboBox1.setSelectedItem(new String("PRODUIT DERIVE")) ;
                 this.jComboBox2.setSelectedItem(new String("POINT PLACEMENT")) ;
                 this.nbp.setEnabled(false) ;
                 this.jButton1.setEnabled(false) ;
                 
             }
                 
                 // if detail_pl is incerted :
                 
                 
                 
                 
                 
            
                                              
                                       // fin detail_pl :       
                                              
                                         
                                         
                                     }
                                          
              
              
              
          }
          
      }else if(point == 1){
          
          this.newStock_arriver = (this.nbp_ob + this.ans) ;
          this.new_prx_pm_arriver = this.pu_p ;
          
          if(stmt.executeUpdate("update stock_pl set stock_dispo = "+this.newStock_arriver+" , prx_pm = "+this.new_prx_pm_arriver+" , p_m_d = "
                  +this.new_prx_pm_arriver+" where magasin = '"+this.magasin_arriver.replaceAll("'", "''")+"' and description = '"+this.description.replaceAll("'", "''")+"'") == 1){
              
              stmt.executeUpdate("update stock_pl set prx_pm = "+this.new_prx_pm_arriver+" , p_m_d = "+this.new_prx_pm_arriver+" where description = '"+this.description.replaceAll("'", "''")+"'") ;
               stmt.executeUpdate("update stock_pl set ap = "+this.ap+" where description = '"+this.description.replaceAll("'", "''")+"'") ;
              
               if(stmt.executeUpdate("insert into stock_detail_pl(cb_op,datej,description,qte,prx_pm,mtt,depart,ndep,arriver,nariv,nderive,perso,type_op,admin, p_m_d, ans_2) VALUES("
                  +this.cb_op+" , '"+jour+"' , '"+this.description+"' , "+this.nbp_ob+" , "
          +this.pu_p+" , "+(this.nbp_ob * this.pu_p)+" , 'ZONE DE DECOUPAGE' , "
          +this.nbp_ob+" , '"+this.magasin_arriver+"' , "+this.nbp_ob+" , "+this.nbp_ob+" , '"
          +"PERSO T"+"' , 'entree' , '"
          + this.login.replaceAll("'", "''")+"' , "+this.pu_p+" , "+this.ans+")" ) == 1 ){
                 
                                              
                                         
                                         // fin detail stock placement :
                                              
                                         // debut detail_pl :
                                             
                   
             if(stmt.executeUpdate("update op_pl_f set etat = 'fermer' where cb = "+this.cb_op) == 1){
                 
                 this.jComboBox1.setSelectedItem(new String("PRODUIT DERIVE")) ;
                 this.jComboBox2.setSelectedItem(new String("POINT PLACEMENT")) ;
                 this.nbp.setEnabled(false) ;
                 this.jButton1.setEnabled(false) ;
                 
             }
                 
                 // if detail_pl is incerted :
                 
                 
                 
                 
                 
            
                                              
                                       // fin detail_pl :       
                                              
                                         
                                         
                                     }
                                          
              
              
              
          }
          
          
      }
          
          
          
           
           
           
           
      
      
      }else if(this.vy == 1){
          
    //      JOptionPane.showMessageDialog(this, "stock existe !! ") ;
          
          float p1 = 0 ;
          float p2 = 0 ;
          
          this.newStock_arriver = (this.oldStock_arriver + this.nbp_ob) ;
          
          p1 = (this.oldStock_arriver * this.old_prx_pm_arriver) ;
          p2 = (this.nbp_ob * this.pu_p) ;
          
          this.new_prx_pm_arriver = ((p1 + p2) / this.newStock_arriver ) ;
          
          if(this.magasin_arriver.equalsIgnoreCase("CHAMBRE FROIDE")){
              
              stmt.executeUpdate("update pmp set pv = "+(this.new_prx_pm_arriver)+" "
           +" where article = '"+this.description+"'") ;
              
             stmt.executeUpdate("update stock1 set pa = "+(this.new_prx_pm_arriver)+" "
           +", pv = "+(this.new_prx_pm_arriver)+" where desi = '"+this.description+"'") ; 
              
               
          }
          
          if(stmt.executeUpdate("update stock_pl set stock_dispo = "+(this.ans + this.nbp_ob)+" , prx_pm = "+this.new_prx_pm_arriver+" "
           +", dtec = '"+jour+"' , p_m_d = "+this.new_prx_pm_arriver +" where magasin = '"+this.magasin_arriver+"' and description = '"+this.description+"'") >= 0){
              
              stmt.executeUpdate("update stock_pl set prx_pm = "+this.new_prx_pm_arriver+" , p_m_d = "+this.new_prx_pm_arriver+" where description = '"+this.description.replaceAll("'", "''")+"'") ;
               stmt.executeUpdate("update stock_pl set ap = "+this.ap+" where description = '"+this.description.replaceAll("'", "''")+"'") ;
              
               if(stmt.executeUpdate("insert into stock_detail_pl(cb_op,datej,description,qte,prx_pm,mtt,depart,ndep,arriver,nariv,nderive,perso,type_op,admin, p_m_d,ans_2) VALUES("
                  +this.cb_op+" , '"+jour+"' , '"+this.description+"' , "+this.nbp_ob+" , "
          + this.pu_p+" , "+(this.nbp_ob * this.pu_p)+" , 'ZONE DE DECOUPAGE' , "
          +this.nbp_ob+" , '"+this.magasin_arriver+"' , "+this.nbp_ob+" , "+this.nbp_ob+" , '"
          +"PERSO T"+"' , 'ENTREE' , '"
          + this.login.replaceAll("'", "''")+"' , "+this.pu_p+" , "+this.ans+")" ) == 1 ){
                 
                                              
                                         
                                         // fin detail stock placement :
                                              
                                         // debut detail_pl :     
                                                  
             if(stmt.executeUpdate("update op_pl_f set etat = 'fermer' where cb = "+this.cb_op) == 1){
                 
                 this.jComboBox1.setSelectedItem(new String("PRODUIT DERIVE")) ;
                 this.jComboBox2.setSelectedItem(new String("POINT PLACEMENT")) ;
                 this.nbp.setEnabled(false) ;
                 this.jButton1.setEnabled(false) ;
                 
             }
                                    
                                         
                                     }
                                          
              
                
              
          }
          
          
         
          
      }
      
       }catch(Exception ex){
       
       JOptionPane.showMessageDialog(null, "CHOISIR UN PRODUIT DERIVE ET REPRENDRE") ;
       
       }
      
      // fin partie unitile :
      
      
          
      //STEP 6: Clean-up environment
 
     // rs.close() ;
      stmt.close();
      conn.close();
      
      
   }catch(SQLException se){
      //Handle errors for JDBC
      se.printStackTrace();
   }catch(Exception e){
      //Handle errors for Class.forName
      e.printStackTrace();
   }finally{
      //finally block used to close resources
      try{
         if(stmt!=null)
            stmt.close();
      }catch(SQLException se2){
      }// nothing we can do
      try{
         if(conn!=null)
            conn.close();
      }catch(SQLException se){
         se.printStackTrace();
      }//end finally try
   }//end try
        
       this.nbp.setText("") ;
       this.jComboBox1.setEnabled(false) ;
       this.jComboBox2.setEnabled(false) ;
        
            ListOp_En_Cours.actuTables() ;
            this.setVisible(false) ;
            
        }else{
            // No option :
            
            
        }
        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
        this.magasin_arriver = "" ;
        this.magasin_arriver = this.jComboBox2.getSelectedItem().toString().replaceAll("'", "''") ;
        
        if("POINT PLACEMENT".equalsIgnoreCase(this.magasin_arriver)){
            this.magasin_arriver = "" ;
           // JOptionPane.showMessageDialog(this, "SELECTIONNER UN POINT DE PLACEMENT SVP ");
        }else{
            
        }
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        this.description = "" ;
        this.description = this.jComboBox1.getSelectedItem().toString().replaceAll("'", "''") ;
        
        if("PRODUIT DERIVE".equalsIgnoreCase(this.description) || "".equalsIgnoreCase(this.magasin_arriver)){
           // JOptionPane.showMessageDialog(this, "SELECTION LE POINT DE PLACEMENT CORRECT ET UN MAGASIN CORRECT SVP ") ;
            
            this.description = "" ;
            
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decoupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decoupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decoupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decoupage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decoupage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel m;
    private javax.swing.JLabel nb;
    private javax.swing.JFormattedTextField nbp;
    private javax.swing.JLabel op;
    private javax.swing.JLabel p2;
    // End of variables declaration//GEN-END:variables
}
