/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HAMZA
 */
public class EditStoctOld extends javax.swing.JFrame {

    /**
     * Creates new form EditStoct
     */
    
      static final String JDBC_DRIVER = "com.mysql.jdbc.Driver" ;  
      static final String DB_URL = "jdbc:mysql://192.168.1.117:3306/transformation" ;
      static final String USER = "root" ;
      static final String PASS = "interco" ;
      
      String magasin = "";
      String famille = "";
      String sfamille = "";
      String dt1 = "";
      String dt2 = "";
      String debutJour = "";
      String finJour = "";
    
    public EditStoctOld() {
        initComponents();
        this.setLocationRelativeTo(null);
        DateFormat datef = new SimpleDateFormat("yyyy-MM-dd") ;
        this.debutJour = datef.format(new Date())+" "+"05" ;
        System.out.println(this.debutJour);
        Calendar cal = Calendar.getInstance();
        cal.setTime(new Date());
        cal.add(Calendar.DAY_OF_YEAR, 1);
        Date tomorrow = cal.getTime();
        this.finJour = datef.format(tomorrow)+" "+"04";
        System.out.println(this.finJour);
        
        
        Connection conn = null ;
         Statement stmt = null  ; 
       
       try{
      Class.forName(JDBC_DRIVER);
        conn = DriverManager.getConnection(DB_URL,USER,PASS);
        stmt = conn.createStatement();
      
      String sql ;
      
       sql = "SELECT * FROM magasins " ;
      
       ResultSet rs = stmt.executeQuery(sql) ;
      
      
     while(rs.next()){
       this.mg.addItem(rs.getString("magasin")) ; 
       
     }
     
     String sql1 ;
      
       sql1 = "SELECT * FROM famille ";
      
       ResultSet rs1 = stmt.executeQuery(sql1) ;
      
      
     while(rs1.next()){
       this.f.addItem(rs1.getString("nom")) ; 
       
     }
      
     rs.close();
      stmt.close();
      conn.close();
   
   }catch(SQLException se){
      se.printStackTrace();
   }catch(Exception e){
      e.printStackTrace();
   }finally{
      try{
         if(stmt!=null)
            stmt.close();
      }catch(SQLException se2){
      try{
         if(conn!=null)
            conn.close();
      }catch(SQLException se){
         se.printStackTrace();
      }
   }
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<String>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        mg = new javax.swing.JComboBox<String>();
        f = new javax.swing.JComboBox<String>();
        sf = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EDITION DE STOCK");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Etat du stock");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        mg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MAGASIN", "TOUS" }));

        f.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FAMILLE", "TOUTES" }));
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        sf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOUS FAMILLE", "TOUTES" }));
        sf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfActionPerformed(evt);
            }
        });

        jButton1.setText("FERMER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mg, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(sf, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(488, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        this.magasin = this.mg.getSelectedItem().toString() ;
        this.famille = this.f.getSelectedItem().toString() ;
        this.sfamille = this.sf.getSelectedItem().toString() ;
        NumberFormat nf3 = NumberFormat.getInstance(new Locale("da", "DK"));
        
        
        if (this.magasin.equals("MAGASIN") && this.famille.equals("FAMILLE") && this.sfamille.equals("SOUS FAMILLE")) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner les champs");
        } else { 
            
            try{
            Class.forName(JDBC_DRIVER);
            Connection connection = DriverManager.getConnection(DB_URL,USER,PASS); 
            Statement statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE ,ResultSet.CONCUR_READ_ONLY); 
            ResultSet resultat = statement.executeQuery(requete(this.magasin, this.famille, this.sfamille));
            
            
            InputStream in = new FileInputStream(new File("\\\\192.168.1.117\\sibycenter\\stockVariation.jrxml")) ;
           //InputStream in = new FileInputStream(new File("D:\\SIBY ARS FINALE V2\\UtpaSibyCenter\\src\\reports\\stockVariation.jrxml")) ;
           
            long vpa, vpv, total_vpa = 0, total_vpv = 0;
            String unite_m;
 
            
            List mlist;
            mlist = new ArrayList<>();
            while(resultat.next()) {
                HashMap<String, Object> m = new HashMap<>(); 
                m.put("cb", resultat.getString("cb"));
                m.put("desi", resultat.getString("desi"));
                m.put("astock", resultat.getInt("astock"));
                m.put("pa", resultat.getInt("pa"));
                m.put("pv", resultat.getInt("pv"));
                unite_m = resultat.getString("um");
                if ("oui".equalsIgnoreCase(unite_m)) {
                    vpa = ((resultat.getInt("pa") * resultat.getInt("astock"))) / 1000;
                    vpv = ((resultat.getInt("pv") * resultat.getInt("astock"))) / 1000;
                } else {
                   vpa = (resultat.getInt("pa") * resultat.getInt("astock"));
                   vpv = (resultat.getInt("pv") * resultat.getInt("astock")); 
                }
               
                m.put("vpa", vpa);
                m.put("vpv", vpv);
                
                total_vpa += vpa;
                total_vpv += vpv;
                
                mlist.add(m);
            }
            
            JRBeanCollectionDataSource jrbean = new JRBeanCollectionDataSource(mlist);
            
            Map<String, Object> para = new HashMap<>();
            para.put("sql", jrbean);
            para.put("total_vpa", nf3.format(total_vpa));
            para.put("total_vpv", nf3.format(total_vpv));
            
            JasperReport report = JasperCompileManager.compileReport(in);
            JasperPrint print = JasperFillManager.fillReport(report, para, new JREmptyDataSource());
            JasperViewer.viewReport(print, false);
            
       }catch(Exception e){
       
           JOptionPane.showMessageDialog(null, e) ;
           System.out.println(e) ;
       
       }
            
        }  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void sfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
       
          String rflle = this.f.getSelectedItem().toString().replaceAll("'", "''") ;

         if(rflle.equalsIgnoreCase("FAMILLE")){
         
             
      this.sf.removeAllItems() ;
      this.sf.addItem("SOUS FAMILLE") ;
      this.sf.addItem("TOUTES") ;
       
             
         }else{
             
              // d :
        
        
             Connection conn = null ;
             Statement  stmt = null ;
       
       try{
      //STEP 2: Register JDBC driver
      Class.forName(JDBC_DRIVER);

      //STEP 3: Open a connection
     // System.out.println("Connecting to database...");
      
      conn = DriverManager.getConnection(DB_URL,USER,PASS);

      //STEP 4: Execute a query
      //System.out.println("Creating statement...");
      stmt = conn.createStatement();
      
      //je crai ma requete
      
      this.sf.removeAllItems() ;
      this.sf.addItem("SOUS FAMILLE") ;
      this.sf.addItem("TOUTES") ;
       
        
       String sql2 ;
      
       sql2 = "SELECT * FROM sfamille WHERE rflle = '"+rflle+"'" ;
      
       ResultSet rs2 = stmt.executeQuery(sql2) ;
      
      
     while(rs2.next()){
  
       this.sf.addItem(rs2.getString("nom")) ;  
          
         
       
     }
    
      rs2.close();
      stmt.close();
      conn.close();
      
      
   }catch(SQLException se){
      //Handle errors for JDBC
      se.printStackTrace();
   }catch(Exception e){
      //Handle errors for Class.forName
      e.printStackTrace();
   }finally{
      //finally block used to close resources
      try{
         if(stmt!=null)
            stmt.close();
      }catch(SQLException se2){
      }// nothing we can do
      try{
         if(conn!=null)
            conn.close();
      }catch(SQLException se){
         se.printStackTrace();
      }//end finally try
   }
         }
        
    }//GEN-LAST:event_fActionPerformed

    private String requete(String magasin, String famille, String sfamille) {
        String requete;
        
        if (magasin.equals("TOUS")) {
            magasin = "";
        }
        if (famille.equals("TOUTES")) {
            famille = "";
        }
        if (sfamille.equals("TOUTES")) {
            sfamille = "";
        }
        if (!"".equalsIgnoreCase(magasin) && "".equalsIgnoreCase(famille) && "".equalsIgnoreCase(sfamille)) {
            requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE maga = '"+magasin+"' ORDER BY desi";
            return requete;
        } else if (!"".equalsIgnoreCase(magasin) && !"".equalsIgnoreCase(famille) && "".equalsIgnoreCase(sfamille)) {
           requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE maga = '"+magasin+"' AND f = '"+famille+"' ORDER BY desi";
            return requete; 
        } else if (!"".equalsIgnoreCase(magasin) && !"".equalsIgnoreCase(famille) && !"".equalsIgnoreCase(sfamille)) {
           requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE maga = '"+magasin+"' AND f = '"+famille+"' AND sf = '"+sfamille+"' ORDER BY desi";
           return requete;  
        } else if ("".equalsIgnoreCase(magasin) && !"".equalsIgnoreCase(famille) && !"".equalsIgnoreCase(sfamille)) {
           requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE f = '"+famille+"' AND sf = '"+sfamille+"' ORDER BY desi";
           return requete;  
        } else if ("".equalsIgnoreCase(magasin) && !"".equalsIgnoreCase(famille) && "".equalsIgnoreCase(sfamille)) {
           requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE f = '"+famille+"' ORDER BY desi";
           return requete;  
        } else if ("".equalsIgnoreCase(magasin) && "".equalsIgnoreCase(famille) && "".equalsIgnoreCase(sfamille)) {
           requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 ORDER BY desi";
            System.out.println("rentré");
           return requete;  
        }
        return "";
    }
    
    private String requete(String magasin, String famille, String sfamille, String dt1, String dt2) {
        String requete;
        
        if (magasin.equals("TOUS")) {
            magasin = "";
        }
        if (famille.equals("TOUTES")) {
            famille = "";
        }
        if (sfamille.equals("TOUTES")) {
            sfamille = "";
        }
        if (!"".equalsIgnoreCase(magasin) && "".equalsIgnoreCase(famille) && "".equalsIgnoreCase(sfamille) && !"".equalsIgnoreCase(dt1) && !"".equalsIgnoreCase(dt2)) {
            requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE maga = '"+magasin+"' AND (datec BETWEEN '"+dt1+"' AND '"+dt2+"') ORDER BY desi";
            return requete;
        } else if (!"".equalsIgnoreCase(magasin) && !"".equalsIgnoreCase(famille) && "".equalsIgnoreCase(sfamille) && !"".equalsIgnoreCase(dt1) && !"".equalsIgnoreCase(dt2)) {
           requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE maga = '"+magasin+"' AND f = '"+famille+"' AND (datec BETWEEN '"+dt1+"' AND '"+dt2+"') ORDER BY desi";
            return requete; 
        } else if (!"".equalsIgnoreCase(magasin) && !"".equalsIgnoreCase(famille) && !"".equalsIgnoreCase(sfamille) && !"".equalsIgnoreCase(dt1) && !"".equalsIgnoreCase(dt2)) {
           requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE maga = '"+magasin+"' AND f = '"+famille+"' AND sf = '"+sfamille+"' AND (datec BETWEEN '"+dt1+"' AND '"+dt2+"') ORDER BY desi";
           return requete;  
        } else if ("".equalsIgnoreCase(magasin) && !"".equalsIgnoreCase(famille) && !"".equalsIgnoreCase(sfamille) && !"".equalsIgnoreCase(dt1) && !"".equalsIgnoreCase(dt2)) {
           requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE f = '"+famille+"' AND sf = '"+sfamille+"' AND (datec BETWEEN '"+dt1+"' AND '"+dt2+"') ORDER BY desi";
           return requete;  
        } else if ("".equalsIgnoreCase(magasin) && !"".equalsIgnoreCase(famille) && "".equalsIgnoreCase(sfamille) && !"".equalsIgnoreCase(dt1) && !"".equalsIgnoreCase(dt2)) {
           requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE f = '"+famille+"' AND (datec BETWEEN '"+dt1+"' AND '"+dt2+"') ORDER BY desi";
           return requete;  
        } else if ("".equalsIgnoreCase(magasin) && "".equalsIgnoreCase(famille) && "".equalsIgnoreCase(sfamille) && !"".equalsIgnoreCase(dt1) && !"".equalsIgnoreCase(dt2)) {
           requete = " SELECT id as id, cb as cb, desi as desi, stock as astock, pa as pa, pv as pv, unite_m as um FROM stock1 WHERE (datec BETWEEN '"+dt1+"' AND '"+dt2+"') ORDER BY desi";
           return requete;  
        }
        return "";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStoctOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStoctOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStoctOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStoctOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStoctOld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> mg;
    private javax.swing.JComboBox<String> sf;
    // End of variables declaration//GEN-END:variables
}
